# Generated by Django 3.2.6 on 2021-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('uuid', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
    ]
